export enum EnvironmentVariableTypeEnum {
  TYPEORM_HOST = 'TYPEORM_HOST',
  TYPEORM_USERNAME = 'TYPEORM_USERNAME',
  TYPEORM_PASSWORD = 'TYPEORM_PASSWORD',
  TYPEORM_DATABASE = 'TYPEORM_DATABASE',
  TYPEORM_PORT = 'TYPEORM_PORT',
  GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID',
  GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET',
  JWT_SECRET = 'JWT_SECRET',
  SERVER_URL = 'SERVER_URL',
  DISCORD_CLIENT_ID = 'DISCORD_CLIENT_ID',
  DISCORD_CLIENT_SECRET = 'DISCORD_CLIENT_SECRET',
}
